name: Deploy to SunilDev

on:
  push:
    branches:
      - main
    paths:
      - 'force-app/**'
      - 'manifest/**'
      - 'sfdx-project.json'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Verify CLI
        run: sf --version

      - name: Authenticate Salesforce Org
        shell: bash
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > ./SFDX_AUTH_URL.txt
          sf org login sfdx-url --sfdx-url-file ./SFDX_AUTH_URL.txt --alias SunilDev --set-default
          rm ./SFDX_AUTH_URL.txt

      - name: Deploy Source to Target Org
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org SunilDev \
            --wait 30
